# Generated by Django 4.1.10 on 2023-07-08 16:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_alter_posts_created_alter_posts_publish'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='blog_post_publish_bb7600_idx',
            old_name='blog_posts_publish_18b59a_idx',
        ),
    ]
