# Generated by Django 4.1.10 on 2023-07-08 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_posts_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 7, 8, 16, 18, 40, 545441, tzinfo=datetime.timezone.utc)),
        ),
    ]
